language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t kamilberdychowski/docker-complex-fibonacci-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kamilberdychowski/docker-complex-fibonacci-test npm test

after_success:
 - docker build -t kamilberdychowski/docker-complex-fibonacci-client ./client
 - docker build -t kamilberdychowski/docker-complex-fibonacci-api ./api
 - docker build -t kamilberdychowski/docker-complex-fibonacci-worker ./worker
 - docker build -t kamilberdychowski/docker-complex-fibonacci-nginx ./nginx
 # login to docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push kamilberdychowski/docker-complex-fibonacci-client
 - docker push kamilberdychowski/docker-complex-fibonacci-api
 - docker push kamilberdychowski/docker-complex-fibonacci-worker
 - docker push kamilberdychowski/docker-complex-fibonacci-nginx
