version: "3"
services: 
  postgres:
    image: "postgres:11-alpine"
  redis:
    image: "redis:5-alpine"
  server:
    build:
      dockerfile: Dockerfile.dev    
      context: ./server
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres_password